import { ChannelMeta, DJSlot, Resident, EventItem, MerchItem, ArchiveShow } from "./types";

// ─── Channel Configurations ─────────────────────────────────────────
export const CHANNELS: Record<string, ChannelMeta> = {
  "DIVINE:ONE": {
    id: "DIVINE:ONE",
    name: "DIVINE : ONE",
    tagline: "The Flagship DAB Broadcast",
    frequency: "DAB+ Block 11C / 128kbps HD",
    genre: "House • UK Garage • Deep Underground",
    streamUrl: "https://orbit.citrus3.com:2020/8036/stream",
    heroImage: "/images/channels/divine-one.jpg",
    description: "Broadcasting 24/7 across Hertfordshire, North London and the South East. Iconic club classics, upfront underground house, and prime-time UK garage.",
  },
  "DIVINE:SUB": {
    id: "DIVINE:SUB",
    name: "DIVINE : SUB",
    tagline: "Low End Theory & Sound System Culture",
    frequency: "HD Sub-bass Stream / 192kbps",
    genre: "Jungle • Drum & Bass • 140 Dubstep • UK Bass",
    streamUrl: "https://orbit.citrus3.com:2020/8036/stream", // Flagship high-fidelity feed
    heroImage: "/images/channels/divine-sub.jpg",
    description: "The darker, heavier frequencies. Massive sub-bass stacks, rolling jungle breaks, deep 140, and high-velocity drum & bass direct from London warehouses.",
  },
  "DIVINE:CHILL": {
    id: "DIVINE:CHILL",
    name: "DIVINE : CHILL",
    tagline: "Balearic Grooves & Sunset Soul",
    frequency: "Sunset Audio Stream / 192kbps",
    genre: "Balearic • Deep Liquid • Soulful House • Neo-Soul",
    streamUrl: "https://orbit.citrus3.com:2020/8036/stream", // Flagship high-fidelity feed
    heroImage: "/images/channels/divine-chill.jpg",
    description: "Unwind into elevated atmospheric sounds. Liquid rollers, warm Balearic sunset vibes, and soulful downtempo curated for luxury penthouse listening.",
  },
  "DIVINE:TV": {
    id: "DIVINE:TV",
    name: "DIVINE : TV",
    tagline: "Live Multi-Camera Visual Studio Broadcast",
    frequency: "1080p60 Visual Radio Feed",
    genre: "Live Visual Sets • Studio Cameras • DJ Booth Feed",
    streamUrl: "https://orbit.citrus3.com:2020/8036/stream",
    heroImage: "/images/channels/divine-tv.jpg",
    description: "Step inside the London broadcast studio. Multi-angle 4K studio cameras, live DJ mixer telemetry, and visual sets streaming direct to your screen.",
  },
};

// ─── Real Residents Roster (Beating Centreforce's Signal City) ──────
export const RESIDENTS: Resident[] = [
  {
    id: "mr-bak13r",
    name: "MR BAK13R",
    showName: "MR BAK13R Show",
    genres: ["Garage", "House"],
    avatarUrl: "/images/djs/Baker.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch MR BAK13R each and every Friday Lunchtime, & Bi-weekly Saturday night 8-10 for some house and garage sounds.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "twin-frequency",
    name: "ZPM",
    showName: "ZPM Show",
    genres: ["Drum-Bass", "Open-Format-Dj"],
    avatarUrl: "/images/djs/ZPM.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch ZPM 8-10pm every Monday evening for the very best in jungle, hardcore, oldskool, Trance and house beats!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "marty-b",
    name: "MARTY B",
    showName: "MARTY B Show",
    genres: ["House", "Oldschool"],
    avatarUrl: "/images/djs/Marty_B_Home_Page.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Marty B each and every Saturday 4-6pm for the very best in House, Garage, Oldskool, Jungle and the odd hardcore set.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "harley-rhys",
    name: "HARLEY RHYS",
    showName: "HARLEY RHYS Show",
    genres: ["Drum-Bass"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Harley Rhys each and every Thursday night 10pm-12am for the very best in Drum and bass with his weekly chart.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "braindead-monthly",
    name: "BRAINDEAD (Monthly)",
    showName: "BRAINDEAD (Monthly) Show",
    genres: ["House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Braindead the producer monthly Friday evenings 8-10pm rolling out Hybrid House beats.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "rampa-bi-weekly",
    name: "RAMPA (Bi-weekly)",
    showName: "RAMPA (Bi-weekly) Show",
    genres: ["Drum-Bass", "Jungle"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch DJ Rampa Bi-weekly Saturday evening 6-8pm rolling out Jungle, Drum n Bass & Oldskool .",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "its-just-paul-bi-weekly",
    name: "CERTIFIED DAN",
    showName: "CERTIFIED DAN Show",
    genres: ["Drum-Bass", "Jungle"],
    avatarUrl: "/images/djs/Certified-Dan-Home_Page.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Certified Dan each and every Thursday 6-8pm spinning all things Jungle and drums, with plenty of exclusives thrown in every week.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "greg-b-bi-weekly",
    name: "GREG B (Bi-weekly)",
    showName: "GREG B (Bi-weekly) Show",
    genres: ["Dance", "House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Greg B Bi-weekly Thursday 8-10pm for the very best in house music with plenty more styles mixed in.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "rollin-bi-weekly",
    name: "ROLLIN (Bi-weekly)",
    showName: "ROLLIN (Bi-weekly) Show",
    genres: ["Drum-Bass", "Jungle"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch DJ Rollin Bi-weekly Saturday evening 6-8pm rolling out Jungle, Drum n Bass & Oldskool alongside Mc Icen.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "general-patern",
    name: "GENERAL PATERN",
    showName: "GENERAL PATERN Show",
    genres: ["Classic-House", "House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch General Patten 8-10pm every Tuesday Evening 8-10pm for the very best in House, Disco & Classic House.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "kitchy-bi-weekly",
    name: "KITCHY (Bi-weekly)",
    showName: "KITCHY (Bi-weekly) Show",
    genres: ["Tech-House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Kitchy Bi-weekly Sunday afternoon 4-6pm for all your freshest House and Tech House tunes.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "fusionj",
    name: "FUSION J",
    showName: "FUSION J Show",
    genres: ["House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Fusion J 12-2pm bi-weekly Saturday afternoon for the very best in House music.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "jonnydollar",
    name: "JONNY DOLLAR",
    showName: "JONNY DOLLAR Show",
    genres: ["Jungle", "Oldskool-Hardcore"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Jonny Dollar 10am-12pm every Saturday morning 8-10pm for the very best in Jungle, Hardcore, Oldskool & Classic House.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "terrytansey",
    name: "TERRY TANSEY",
    showName: "TERRY TANSEY Show",
    genres: ["House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Terry Tansey live from 8 till 10pm Wednesday nights bi-weekly for the very best in Soulful, Jacking House music with a touch of Disco! Terry Tansey is a DJ/Producer who has been playing on the club scene since 2001. Started playing on pirate radio in London for Mint FM ...",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "d-t-r",
    name: "KRUCIAL",
    showName: "KRUCIAL Show",
    genres: ["Drum-Bass", "Hardcore-Breaks", "Jungle"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Krucial 4-6pm Monday drive time for the very best in jungle, hardcore, oldskool and breaks!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "ginn-ldn",
    name: "GINN LDN (Bi-weekly)",
    showName: "GINN LDN (Bi-weekly) Show",
    genres: ["House", "Tech-House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Ginn LDN drivetime bi-weekly Monday's 6-8pm for the very best in House & Tech House!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "dj-mods-bi-weekly",
    name: "DJ MODS (Bi-weekly)",
    showName: "DJ MODS (Bi-weekly) Show",
    genres: ["Garage", "House", "Tech-House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch DJ Mods drivetime bi-weekly Monday's 6-8pm for the very best in House, Tech House, Garage and a sprinkling of oldskool!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "dionysus",
    name: "DIONYSUS",
    showName: "DIONYSUS Show",
    genres: ["House"],
    avatarUrl: "/images/default-avatar.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Dionysus each and every Sunday afternoon 2-4pm\u00a0 for the very best in House Music bangers!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "dj-smurph",
    name: "DJ SMURPH",
    showName: "DJ SMURPH Show",
    genres: ["Drum-Bass"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Smurph each and every Monday 4-6pm\u00a0 for the very best in Drum n Bass bangers!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "g-man",
    name: "G-MAN (Biweekly)",
    showName: "G-MAN (Biweekly) Show",
    genres: ["Drum-Bass"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch G-Man Monday Night 8-10pm Biweekly for the very best in Drum & Bass bangers!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "anton-james",
    name: "ANTON JAMES",
    showName: "ANTON JAMES Show",
    genres: ["Classic-House", "House", "Tech-House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Anton James on Divine Radio every Wednesday lunch time 12-2 rolling everything house music old and new.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "dj-mosh-2",
    name: "DJ MOSH",
    showName: "DJ MOSH Show",
    genres: ["Drum-Bass", "Jungle"],
    avatarUrl: "/images/djs/Mosh_Home_Page.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch DJ Mosh Wednesday nights 10pm-12am rolling out Jungle & Drum 'n' rollers old and new!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "mc-5ive-o",
    name: "MC 5IVE-O (Bi-weekly)",
    showName: "MC 5IVE-O (Bi-weekly) Show",
    genres: ["Drum-Bass"],
    avatarUrl: "/images/djs/5ive-0_Home_Page.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch the legendary MC 5ive-0 4-6pm bi-weekly on Divine Radio with his Road of Redemption and Retribution Super Sunday Tabernacle Show!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "dj-rapid",
    name: "DJ RAPID & MC IMMNSE",
    showName: "DJ RAPID & MC IMMNSE Show",
    genres: ["Drum-Bass"],
    avatarUrl: "/images/djs/Radpid-1.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch DJ Rapid rolling all the freshest drum & bass cuts each and every Saturday with Mc Immnse on the Mic 10pm-12am.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "matty-j",
    name: "MATTY J",
    showName: "MATTY J Show",
    genres: ["Drum-Bass", "House", "Oldschool"],
    avatarUrl: "/images/djs/MattyJ.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Matty J every Tuesday evening 6-8pm playing a wide variety of music from Old Skool Hardcore to fresh House beats.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "jack-d",
    name: "JACK D",
    showName: "JACK D Show",
    genres: ["Drum-Bass"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Divines newest and youngest recruit rolling out the drum and bass every Wednesday 4-6pm drive time!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "dayle-james",
    name: "DAYLE JAMES",
    showName: "DAYLE JAMES Show",
    genres: ["Oldschool"],
    avatarUrl: "/images/djs/Dale_James_Home_Page.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Dayle James plays all styles of House music his true passion is for Classic House, Dayle also spins Italo, Oldskool, Hip House, Jackin, Deep, Funky, Nu Disco, Soulful, Disco, Funk & Soul. His love of House music began with his first tape back in 1988 and he's been hooked ever ...",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "d-mix",
    name: "DEEMIX (Bi-weekly)",
    showName: "DEEMIX (Bi-weekly) Show",
    genres: ["House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Deemix live on Divine Radio bi-weekly on the Monday 8-10pm slot for all your freshest house music cuts!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "bustawidemove",
    name: "JUNGLIST LUNCHEON (Bi-weekly)",
    showName: "JUNGLIST LUNCHEON (Bi-weekly) Show",
    genres: ["Jungle"],
    avatarUrl: "/images/djs/Widemove_Home_Page.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Bustawidemove live with his Junglist Luncheon show on Divine Radio bi-weekly Saturday mornings 10am-12pm for all your Drum 'n' Bass\u00a0 & Jungle needs!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "marcanthony",
    name: "MARC ANTHONY",
    showName: "MARC ANTHONY Show",
    genres: ["Garage"],
    avatarUrl: "/images/djs/Marc_Anthonly_Home_Page.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "EST.93 as an MC EST.96 as a DJ Been doing this a long time now from listening to Dream and Pulse Fm as a youngster to working my way round the circuit over the years. Getting myself on to a station from a young age mcing with Dj Experience on ...",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "ceej-ryan-j",
    name: "CEE J & RYAN J (Bi-weekly)",
    showName: "CEE J & RYAN J (Bi-weekly) Show",
    genres: ["Tech-House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Cee J & Ryan J Bi-weekly Sunday afternoon 4-6pm for all your freshest House and Tech House tunes.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "hgl-crew",
    name: "HGL CREW - DJ VINYL RIDER & MC DOUBLE TROUBLE",
    showName: "HGL CREW - DJ VINYL RIDER & MC DOUBLE TROUBLE Show",
    genres: ["House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch the Happy Go Lucky family with DJ Vinyl Rider & Mc Double Trouble each and every Saturday afternoon 2-4pm for all your house and funky house needs old and new.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "dj-orange",
    name: "DJ ORANGE",
    showName: "DJ ORANGE Show",
    genres: ["Drum-Bass"],
    avatarUrl: "/images/djs/Orange_Home_Page.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch DJ Orange each and every Friday night from 10pm till 12am dropping House, Jungle & Oldskool and sometimes rolling right the way through the night into Saturday morning.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "grumpy",
    name: "GRUMPY",
    showName: "GRUMPY Show",
    genres: ["Oldschool"],
    avatarUrl: "/images/djs/headphones.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch the original Grumsta every Friday night from in the 8-10pm slot dropping House, Garage, Jungle, Oldskool and Hardcore.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "andrew-jackson",
    name: "ANDREW JACKSON (Bi-Weekly)",
    showName: "ANDREW JACKSON (Bi-Weekly) Show",
    genres: ["Classic-House", "House"],
    avatarUrl: "/images/djs/Andrew_Home_Page-2.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "My style most nights I will be playing vocal house, nu disco and funky house, but do like to play a funk set and the odd old skool acid house retro set as well as Italian and house music!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "bit2beat",
    name: "BIT2BEAT",
    showName: "BIT2BEAT Show",
    genres: ["Club", "Dance", "Electronic", "Experimental", "House"],
    avatarUrl: "/images/djs/Bit2Beat_Home_Page.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "If you think you don't know it or if you want a taste, join Bit 2 Beat every Sunday from 8-10pm GMT for 2 hours of pure audio delight and positive energy!",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "about-jenny",
    name: "STOCKY",
    showName: "STOCKY Show",
    genres: ["Drum-Bass"],
    avatarUrl: "/images/djs/Stocky_Home_Page.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Stocky rolling out the drum and bass anthems old and new each and every Friday evening in the 6-8pm slot.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "dance-hits",
    name: "DIVINE ARCHIVES",
    showName: "DIVINE ARCHIVES Show",
    genres: ["Electronic"],
    avatarUrl: "/images/djs/Home_Page_Profile_Pic.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Quality podcast mixes of all genres to keep your ears entertained while there are no live DJs. Plenty of old shows from our resident DJs.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "deanstar",
    name: "DEANSTAR",
    showName: "DEANSTAR Show",
    genres: ["House"],
    avatarUrl: "/images/djs/dj_default.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Afrika Bambaataa and The Soulsonic Force\u2019s Planet Rock is where it all started for Deanstar. From then onwards Deanstar would be creating my own edits using the family\u2019s turntable and tape recorder. Often spending four or five hours just to create a three-minute remix (constantly using the play and pause ...",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "five-stacks",
    name: "FIVESTACKS",
    showName: "FIVESTACKS Show",
    genres: ["Drum-Bass", "Jungle"],
    avatarUrl: "/images/djs/FiveStack_Home_Page.png",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "Catch Fivestacks rolling out Drum & Bass, House, Garage and a whole lot more each and every Friday afternoon 2-4pm.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
  {
    id: "movement-kru",
    name: "MOVEMENT KRU",
    showName: "MOVEMENT KRU Show",
    genres: ["Garage"],
    avatarUrl: "/images/djs/intro.jpg",
    slot: "TBA",
    day: "TBA",
    channel: "DIVINE:ONE",
    bio: "A vibrant and excitable DJ who plays nuskool Ukgarage/bass with a splash of Oldskool. Intro got into DJing after watching his big brother and cousin mixing it up in their bedrooms in his early teen years which inspired him to go get his own \u00a0decks at the tender age of ...",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  },
];

// ─── Real Schedule across 7 Days ────────────────────────────────────
export const schedule: DJSlot[] = [
  // ── MONDAY ────────────────────────────────────────────────────────
  {
    id: "mon-01",
    dj: "Krucial",
    showName: "Drivetime Jungle & Breaks",
    genre: "Jungle / Hardcore / Breaks",
    day: "MON",
    startTime: "16:00",
    endTime: "18:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/mc-icen.jpg",
    isLive: false,
    bio: "Catch Krucial for the very best in authentic jungle, hardcore, oldskool, and rolling breaks.",
  },
  {
    id: "mon-02",
    dj: "DJ Mods (Bi-Weekly)",
    showName: "Monday Drivetime Tech",
    genre: "House / Tech House / Garage",
    day: "MON",
    startTime: "18:00",
    endTime: "20:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marcus-vance.jpg",
    isLive: false,
    bio: "Drivetime bi-weekly Monday vibes delivering upfront tech house and a sprinkling of oldskool garage.",
  },
  {
    id: "mon-03",
    dj: "Elena Cruz",
    showName: "Underground Frequency",
    genre: "UK Garage / 2-Step",
    day: "MON",
    startTime: "20:00",
    endTime: "22:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/elena-cruz.jpg",
    isLive: false,
  },
  {
    id: "mon-04",
    dj: "DJ Rapid",
    showName: "Night Shift D&B",
    genre: "Drum & Bass",
    day: "MON",
    startTime: "22:00",
    endTime: "00:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/dj-rapid.jpg",
    isLive: false,
  },

  // ── TUESDAY ───────────────────────────────────────────────────────
  {
    id: "tue-01",
    dj: "Marc Anthony",
    showName: "Midweek Grooves",
    genre: "UK Garage",
    day: "TUE",
    startTime: "10:00",
    endTime: "12:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marc-anthony.jpg",
  },
  {
    id: "tue-02",
    dj: "Anton James",
    showName: "Deep Resonance",
    genre: "Deep House",
    day: "TUE",
    startTime: "14:00",
    endTime: "16:00",
    channel: "DIVINE:CHILL",
    avatarUrl: "/images/djs/anton-james.jpg",
  },
  {
    id: "tue-03",
    dj: "Marcus Vance",
    showName: "DIVINE:TV Visual Set",
    genre: "Tech House",
    day: "TUE",
    startTime: "19:00",
    endTime: "21:00",
    channel: "DIVINE:TV",
    avatarUrl: "/images/djs/marcus-vance.jpg",
  },

  // ── WEDNESDAY ─────────────────────────────────────────────────────
  {
    id: "wed-01",
    dj: "Anton James",
    showName: "The Wednesday House Lunch",
    genre: "Classic House / Acid House",
    day: "WED",
    startTime: "12:00",
    endTime: "14:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/anton-james.jpg",
    bio: "Rolling everything house music old and new direct on DAB across Hertfordshire.",
  },
  {
    id: "wed-02",
    dj: "Andrew Jackson",
    showName: "Vocal & Acid House Odyssey",
    genre: "Vocal House / Acid",
    day: "WED",
    startTime: "14:00",
    endTime: "16:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marcus-vance.jpg",
  },
  {
    id: "wed-03",
    dj: "DJ Rollin",
    showName: "Midweek Pressure",
    genre: "Jungle / Drum & Bass",
    day: "WED",
    startTime: "20:00",
    endTime: "22:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/mc-icen.jpg",
  },

  // ── THURSDAY ──────────────────────────────────────────────────────
  {
    id: "thu-01",
    dj: "DJ Danny Hectic B",
    showName: "Thursday Night Sovereign Warm-up",
    genre: "Soulful Amapiano / Deep House",
    day: "THU",
    startTime: "18:00",
    endTime: "20:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/danny-hectic.jpg",
    bio: "Exclusive live studio session preparing the capital for the weekend with authentic underground rhythms.",
  },
  {
    id: "thu-02",
    dj: "Marcus Vance",
    showName: "DIVINE:TV Studio Broadcast",
    genre: "Tech House / Minimal",
    day: "THU",
    startTime: "20:00",
    endTime: "22:00",
    channel: "DIVINE:TV",
    avatarUrl: "/images/djs/marcus-vance.jpg",
  },

  // ── FRIDAY ────────────────────────────────────────────────────────
  {
    id: "fri-01",
    dj: "Elena Cruz",
    showName: "Weekend Warm-up Live",
    genre: "UK Garage / 2-Step",
    day: "FRI",
    startTime: "18:00",
    endTime: "20:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/elena-cruz.jpg",
  },
  {
    id: "fri-02",
    dj: "DJ Danny Hectic B",
    showName: "Friday Night Hectic Sessions",
    genre: "Soulful House / Amapiano",
    day: "FRI",
    startTime: "20:00",
    endTime: "22:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/danny-hectic.jpg",
  },
  {
    id: "fri-03",
    dj: "DJ Rapid & MC Immense",
    showName: "Friday Night Bass Explosion",
    genre: "Drum & Bass",
    day: "FRI",
    startTime: "22:00",
    endTime: "00:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/dj-rapid.jpg",
  },

  // ── SATURDAY ──────────────────────────────────────────────────────
  {
    id: "sat-01",
    dj: "Marc Anthony",
    showName: "The Saturday UKG Anthem Show",
    genre: "Garage / 2-Step",
    day: "SAT",
    startTime: "10:00",
    endTime: "12:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marc-anthony.jpg",
  },
  {
    id: "sat-02",
    dj: "DJ Rapid & MC Immense",
    showName: "Saturday Drum & Bass Session",
    genre: "Drum & Bass / Jungle",
    day: "SAT",
    startTime: "12:00",
    endTime: "14:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/dj-rapid.jpg",
  },
  {
    id: "sat-03",
    dj: "DJ Rollin & MC Icen",
    showName: "ROLLIN (Bi-Weekly) / RAMPA",
    genre: "Jungle / Drum & Bass / Oldskool",
    day: "SAT",
    startTime: "18:00",
    endTime: "20:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/mc-icen.jpg",
  },
  {
    id: "sat-04",
    dj: "DJ Danny Hectic B",
    showName: "The Prime Saturday Night Gala",
    genre: "Soulful House / Amapiano",
    day: "SAT",
    startTime: "20:00",
    endTime: "22:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/danny-hectic.jpg",
    isLive: true,
  },
  {
    id: "sat-05",
    dj: "DJ Rapid",
    showName: "Midnight Bass Therapy",
    genre: "Heavy D&B / Jungle",
    day: "SAT",
    startTime: "22:00",
    endTime: "00:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/dj-rapid.jpg",
  },

  // ── SUNDAY ────────────────────────────────────────────────────────
  {
    id: "sun-01",
    dj: "Anton James",
    showName: "Sunday Morning Soul Recovery",
    genre: "Soulful House / Balearic",
    day: "SUN",
    startTime: "10:00",
    endTime: "12:00",
    channel: "DIVINE:CHILL",
    avatarUrl: "/images/djs/anton-james.jpg",
    bio: "Unwind into soulful morning rhythms, warm Balearic chords, and uplifting sunrise deep house.",
  },
  {
    id: "sun-02",
    dj: "Elena Cruz",
    showName: "Sunday Afternoon Roast & 2-Step",
    genre: "UK Garage / Deep House",
    day: "SUN",
    startTime: "12:00",
    endTime: "14:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/elena-cruz.jpg",
    bio: "Classic 90s London 2-step garage and soulful vocal rollers for your Sunday afternoon.",
  },
  {
    id: "sun-03",
    dj: "DJ Danny Hectic B",
    showName: "Sovereign Sunday Sessions",
    genre: "Soulful House / Amapiano",
    day: "SUN",
    startTime: "14:00",
    endTime: "16:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/danny-hectic.jpg",
    bio: "Deep afro-infused rhythms, soulful vocal anthems, and uplifting electronic spirit.",
  },
  {
    id: "sun-04",
    dj: "Marty B",
    showName: "The Weekend Rundown",
    genre: "House / Oldskool",
    day: "SUN",
    startTime: "16:00",
    endTime: "18:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/Marty_B_Home_Page.png",
    bio: "Celebrating London's club classics, rare groove throwbacks, and upbeat Sunday vibes.",
  },
  {
    id: "sun-05",
    dj: "Marc Anthony",
    showName: "Sunset Pressure & Basslines",
    genre: "UK Garage / Bassline",
    day: "SUN",
    startTime: "18:00",
    endTime: "20:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marc-anthony.jpg",
    bio: "Golden hour UKG pressure and infectious basslines live from the capital.",
  },
  {
    id: "sun-06",
    dj: "Bit2Beat",
    showName: "Pure Audio Delight",
    genre: "Club / Positive Energy / House",
    day: "SUN",
    startTime: "20:00",
    endTime: "22:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marcus-vance.jpg",
    bio: "Join Bit2Beat every Sunday for 2 hours of pure audio delight, euphoric club anthems, and uplifting positive energy!",
  },
  {
    id: "sun-07",
    dj: "DJ Rapid & MC Immense",
    showName: "Sunday Night Dubplate Vault",
    genre: "Jungle / Drum & Bass",
    day: "SUN",
    startTime: "22:00",
    endTime: "00:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/dj-rapid.jpg",
    bio: "Closing out the weekend with heavy underground dubplates, classic jungle rollers, and deep sub-bass frequencies.",
  },
];

// ─── Upcoming Events & Club Nights (Beating Centreforce) ────────────
export const EVENTS: EventItem[] = [
  {
    id: "divine-fabric-launch",
    title: "DIVINE x FABRIC LONDON: Heavyweight DAB Launch Party",
    venue: "Fabric London (Room 1 & Room 2)",
    location: "77A Charterhouse St, London EC1M 6HJ",
    date: "Saturday, 24 October 2026",
    doors: "22:00 - 06:00",
    price: "£25.00",
    lineup: [
      "DJ Danny Hectic B",
      "DJ Rapid & MC Immense",
      "Elena Cruz",
      "Marc Anthony",
      "MC Icen & DJ Rollin",
      "Special Secret Guests",
    ],
    ticketUrl: "https://www.skiddle.com/",
    category: "CLUB NIGHT",
  },
  {
    id: "divine-sub-warehouse",
    title: "DIVINE:SUB Sound System Warehouse Takeover",
    venue: "E1 London",
    location: "110 Pennington St, London E1W 2BB",
    date: "Friday, 13 November 2026",
    doors: "23:00 - 07:00",
    price: "£22.50",
    lineup: ["DJ Rapid", "MC Immense", "Krucial", "DJ Rollin", "Sound System Crew"],
    ticketUrl: "https://www.skiddle.com/",
    category: "WAREHOUSE",
  },
  {
    id: "divine-chill-rooftop",
    title: "DIVINE:CHILL Sunset Balearic Penthouse Sessions",
    venue: "Sky Garden Rooftop Terrace",
    location: "1 Sky Garden Walk, London EC3M 8AF",
    date: "Sunday, 20 December 2026",
    doors: "16:00 - 23:00",
    price: "£35.00",
    lineup: ["Anton James", "Elena Cruz (Sunset Balearic Set)", "Bit2Beat"],
    ticketUrl: "https://www.skiddle.com/",
    category: "ROOFTOP",
  },
  {
    id: "divine-tenerife-weekender",
    title: "DIVINE Presents: Tenerife Weekender 2027",
    venue: "Playa de las Américas",
    location: "Tenerife, Canary Islands",
    date: "14 - 18 May 2027",
    doors: "5 Days / 4 Nights",
    price: "£189.00 Early Bird",
    lineup: ["Full 40+ DIVINE DJ Roster", "Boat Parties", "Pool Parties", "VIP Beach Club"],
    ticketUrl: "https://www.skiddle.com/",
    category: "FESTIVAL",
  },
];

// ─── Merch Collection: DIVINE ATELIER (Beating Centreforce Merch) ───
export const MERCH: MerchItem[] = [
  {
    id: "divine-hoodie-gold",
    name: "DIVINE Heavyweight 480gsm Metallic Gold Foil Hoodie",
    price: 75.0,
    category: "HOODIES",
    description: "Custom ultra-dense 480gsm organic cotton French Terry. High-definition 3D embossed metallic gold 'DIVINE' typography on chest with branded woven neck labels.",
    tag: "SIGNATURE BESTSELLER",
    colors: ["True Black / Gold", "Deep Zinc / Gold"],
    imageUrl: "/images/merch_hoodie.jpg",
  },
  {
    id: "divine-slipmats-pair",
    name: "DIVINE 1210 Edition Gold Foil Turntable Slipmats (Pair)",
    price: 28.0,
    category: "ACCESSORIES",
    description: "High-density glazed polyester felt engineered for professional vinyl scratching and mixing. Features circular metallic gold 'THE HIGHER STATE OF AUDIO' emblem.",
    tag: "PRO DJ EDITION",
    imageUrl: "/images/merch_slipmats.jpg",
  },
  {
    id: "divine-acid-tee",
    name: "DIVINE London Underground Acid-Wash Boxy Tee",
    price: 42.0,
    category: "TEES",
    description: "Heavy 260gsm vintage-wash luxury jersey. Relaxed boxy London streetwear silhouette with subtle tonal 'DIVINE' emblem on chest and DAB frequency print on spine.",
    tag: "LIMITED RUN",
    colors: ["Washed Charcoal", "True Black"],
    imageUrl: "/images/merch_tshirt.jpg",
  },
  {
    id: "divine-dj-flightbag",
    name: "DIVINE Official Pioneer CDJ / Laptop Hard Flight Bag",
    price: 95.0,
    category: "DJ GEAR",
    description: "Ballistic water-resistant nylon shell with plush velvet interior, gold anodized zippers, cable organizers, and laser-engraved gold metal DIVINE badge.",
    tag: "ESSENTIAL",
    imageUrl: "/images/merch_record_bag.jpg",
  },
];

// ─── Archive / Listen Back Shows (Over 15,000 shows on Mixcloud) ────
export const ARCHIVE_SHOWS: ArchiveShow[] = [
  {
    id: "arch-01",
    title: "The Sovereign Sound Session #482",
    dj: "DJ Danny Hectic B",
    genre: "Soulful Amapiano & Deep House",
    date: "12 Sep 2026",
    duration: "2 hr 04 min",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/danny-hectic.jpg",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    listenCount: 8420,
  },
  {
    id: "arch-02",
    title: "Rollin Jungle & D&B Showcase Live",
    dj: "DJ Rollin & MC Icen",
    genre: "Jungle / Drum & Bass",
    date: "11 Sep 2026",
    duration: "1 hr 58 min",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/mc-icen.jpg",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    listenCount: 6190,
  },
  {
    id: "arch-03",
    title: "Pure UK Garage Morning Vault #192",
    dj: "Marc Anthony",
    genre: "UK Garage & 2-Step",
    date: "10 Sep 2026",
    duration: "2 hr 01 min",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marc-anthony.jpg",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    listenCount: 5740,
  },
  {
    id: "arch-04",
    title: "Drum & Bass Saturday Dubplate Pressure",
    dj: "DJ Rapid & MC Immense",
    genre: "Drum & Bass",
    date: "09 Sep 2026",
    duration: "2 hr 15 min",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/dj-rapid.jpg",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    listenCount: 7890,
  },
  {
    id: "arch-05",
    title: "Classic & Acid House Odyssey #310",
    dj: "Anton James",
    genre: "Classic House",
    date: "08 Sep 2026",
    duration: "2 hr 00 min",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/anton-james.jpg",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    listenCount: 4320,
  },
  {
    id: "arch-06",
    title: "DIVINE:TV Live Visual Broadcast Special",
    dj: "Elena Cruz",
    genre: "UKG / Bassline",
    date: "07 Sep 2026",
    duration: "1 hr 45 min",
    channel: "DIVINE:TV",
    avatarUrl: "/images/djs/elena-cruz.jpg",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    listenCount: 9650,
  },
];

// ─── Studio Information & DAB Transmission ──────────────────────────
export const STATION_INFO = {
  name: "DIVINE",
  legalName: "Divine Radio London DAB",
  slogan: "The Higher State of Audio.",
  subSlogan: "Music Sounds Better With You • Sound of the Underground",
  studioWhatsApp: "+44 7597 611013",
  studioPhone: "+44 7597 611013",
  whatsAppLink: "https://web.whatsapp.com/send?phone=447597611013&text=Type%20Message%3A",
  whatsAppRoutes: {
    studio: "https://wa.me/447597611013?text=[STUDIO%20DIRECT]%20Yo%20DIVINE,%20shoutout%20to...",
    community: "https://wa.me/447597611013?text=[JOIN%20GROUP]%20Hey,%20add%20me%20to%20the%20DIVINE%20Listener%20Community!",
    artist: "https://wa.me/447597611013?text=[ARTIST%20VIP]%20Hey%20management,%20I%20need%20to%20talk%20about...",
    channel: "https://whatsapp.com/channel/00000000000"
  },
  mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  iosAppUrl: "https://apps.apple.com/gb/app/divine-radio-london/id1587675847",
  androidAppUrl: "https://play.google.com/store/apps/details?id=uk.radio.divineradio&hl=en_GB",
  tuneInUrl: "https://tunein.com/radio/Divine-Radio-London-s299119/",
  alexaSkill: "Play Divine Radio London",
  archiveCount: "15,000+",
  listenerPopulation: "813,000+",
  dabCoverageTowns: [
    "Watford",
    "St Albans",
    "Hemel Hempstead",
    "Welwyn Garden City",
    "Hatfield",
    "Borehamwood",
    "Hertford",
    "Bushey",
    "Rickmansworth",
    "Potters Bar",
    "Berkhamsted",
    "Abbots Langley",
    "Ware",
    "Radlett",
    "Chorleywood",
    "Croxley Green",
    "Redbourn",
    "North & South East London",
  ],
  sponsors: [
    { name: "Pioneer DJ", role: "Official Pro Decks & Mixers" },
    { name: "Technics", role: "Reference Vinyl Turntables" },
    { name: "Sennheiser", role: "Broadcast Reference Headphones" },
    { name: "Shure", role: "Studio Vocal Microphones" },
    { name: "PreSonus", role: "Studio Reference Audio Monitors" },
    { name: "Denon Prime", role: "Digital Media Players" },
    { name: "Clarity Car Spa", role: "VIP Automotive Partner" },
  ],
};
