import { ChannelMeta, DJSlot, Resident, EventItem, MerchItem, ArchiveShow } from "./types";

// ─── Channel Configurations ─────────────────────────────────────────
export const CHANNELS: Record<string, ChannelMeta> = {
  "DIVINE:ONE": {
    id: "DIVINE:ONE",
    name: "DIVINE : ONE",
    tagline: "The Flagship DAB Broadcast",
    frequency: "DAB+ Block 11C / 128kbps HD",
    genre: "House • UK Garage • Deep Underground",
    streamUrl: "https://orbit.citrus3.com:2020/8036/stream",
    heroImage: "/images/channels/divine-one.jpg",
    description: "Broadcasting 24/7 across Hertfordshire, North London and the South East. Iconic club classics, upfront underground house, and prime-time UK garage.",
  },
  "DIVINE:SUB": {
    id: "DIVINE:SUB",
    name: "DIVINE : SUB",
    tagline: "Low End Theory & Sound System Culture",
    frequency: "HD Sub-bass Stream / 192kbps",
    genre: "Jungle • Drum & Bass • 140 Dubstep • UK Bass",
    streamUrl: "https://orbit.citrus3.com:2020/8036/stream", // Flagship high-fidelity feed
    heroImage: "/images/channels/divine-sub.jpg",
    description: "The darker, heavier frequencies. Massive sub-bass stacks, rolling jungle breaks, deep 140, and high-velocity drum & bass direct from London warehouses.",
  },
  "DIVINE:CHILL": {
    id: "DIVINE:CHILL",
    name: "DIVINE : CHILL",
    tagline: "Balearic Grooves & Sunset Soul",
    frequency: "Sunset Audio Stream / 192kbps",
    genre: "Balearic • Deep Liquid • Soulful House • Neo-Soul",
    streamUrl: "https://orbit.citrus3.com:2020/8036/stream", // Flagship high-fidelity feed
    heroImage: "/images/channels/divine-chill.jpg",
    description: "Unwind into elevated atmospheric sounds. Liquid rollers, warm Balearic sunset vibes, and soulful downtempo curated for luxury penthouse listening.",
  },
  "DIVINE:TV": {
    id: "DIVINE:TV",
    name: "DIVINE : TV",
    tagline: "Live Multi-Camera Visual Studio Broadcast",
    frequency: "1080p60 Visual Radio Feed",
    genre: "Live Visual Sets • Studio Cameras • DJ Booth Feed",
    streamUrl: "https://orbit.citrus3.com:2020/8036/stream",
    heroImage: "/images/channels/divine-tv.jpg",
    description: "Step inside the London broadcast studio. Multi-angle 4K studio cameras, live DJ mixer telemetry, and visual sets streaming direct to your screen.",
  },
};

// ─── Real Residents Roster (Beating Centreforce's Signal City) ──────
export const RESIDENTS: Resident[] = [
  {
    id: "danny-hectic",
    name: "DJ Danny Hectic B",
    showName: "The Sovereign Sound Session",
    genres: ["Soulful House", "Amapiano", "Deep Underground"],
    avatarUrl: "/images/djs/danny-hectic.jpg",
    slot: "20:00 - 22:00",
    day: "Saturday",
    channel: "DIVINE:ONE",
    bio: "Pioneer of the underground soulful house and authentic Amapiano movement in the UK. Creator of the Hectic sound with over two decades on London airwaves.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    badge: "HEADLINE RESIDENT",
  },
  {
    id: "dj-rapid",
    name: "DJ Rapid & MC Immense",
    showName: "The Drum & Bass Showcase",
    genres: ["Drum & Bass", "Jungle", "Jump Up"],
    avatarUrl: "/images/djs/dj-rapid.jpg",
    slot: "12:00 - 14:00 & 22:00 - 00:00",
    day: "Saturday",
    channel: "DIVINE:SUB",
    bio: "Delivering the freshest drum & bass dubplates and relentless jungle energy every Saturday, hosted by the legendary MC Immense on mic duties.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    badge: "SATURDAY PRIME",
  },
  {
    id: "marc-anthony",
    name: "Marc Anthony",
    showName: "Pure UK Garage Morning",
    genres: ["UK Garage", "2-Step", "Speed Garage"],
    avatarUrl: "/images/djs/marc-anthony.jpg",
    slot: "10:00 - 12:00",
    day: "Saturday",
    channel: "DIVINE:ONE",
    bio: "A true London garage authority. From 90s classic vocal anthems to upfront bass-heavy 2-step cuts, Marc Anthony defines Saturday morning dance radio.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    badge: "GARAGE PIONEER",
  },
  {
    id: "elena-cruz",
    name: "Elena Cruz",
    showName: "London 2-Step Horizon",
    genres: ["UKG", "Future Garage", "Bassline"],
    avatarUrl: "/images/djs/elena-cruz.jpg",
    slot: "18:00 - 20:00",
    day: "Friday",
    channel: "DIVINE:ONE",
    bio: "One of London's fastest rising selectors, known for infectious vinyl blends, rolling syncopated rhythms, and unmatched energy behind the decks.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    badge: "EXCLUSIVE RESIDENT",
  },
  {
    id: "mc-icen-rollin",
    name: "DJ Rollin & MC Icen",
    showName: "Rollin Bi-Weekly Sessions",
    genres: ["Jungle", "Oldskool", "Drum & Bass"],
    avatarUrl: "/images/djs/mc-icen.jpg",
    slot: "18:00 - 20:00",
    day: "Saturday",
    channel: "DIVINE:SUB",
    bio: "Bi-weekly prime time sessions tearing up the airwaves with authentic sound system jungle, vintage breakbeats, and iconic live vocal hosting.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    badge: "BI-WEEKLY ANCHOR",
  },
  {
    id: "anton-james",
    name: "Anton James",
    showName: "Classic House Odyssey",
    genres: ["Classic House", "Acid House", "Tech House"],
    avatarUrl: "/images/djs/anton-james.jpg",
    slot: "12:00 - 14:00",
    day: "Wednesday",
    channel: "DIVINE:ONE",
    bio: "Broadcast veteran delivering Wednesday lunchtime masterclasses spanning three decades of Chicago, Detroit, and London house music heritage.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    badge: "HOUSE CURATOR",
  },
  {
    id: "marcus-vance",
    name: "Marcus Vance",
    showName: "The Gold Standard",
    genres: ["Tech House", "Minimal Deep Tech", "Melodic"],
    avatarUrl: "/images/djs/marcus-vance.jpg",
    slot: "20:00 - 22:00",
    day: "Thursday",
    channel: "DIVINE:TV",
    bio: "Resident for DIVINE:TV live studio visual broadcast, bringing hypnotic tech house grooves and bespoke visual lighting production to the screen.",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    badge: "DIVINE:TV RESIDENT",
  },
];

// ─── Real Schedule across 7 Days ────────────────────────────────────
export const schedule: DJSlot[] = [
  // ── MONDAY ────────────────────────────────────────────────────────
  {
    id: "mon-01",
    dj: "Krucial",
    showName: "Drivetime Jungle & Breaks",
    genre: "Jungle / Hardcore / Breaks",
    day: "MON",
    startTime: "16:00",
    endTime: "18:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/mc-icen.jpg",
    isLive: false,
    bio: "Catch Krucial for the very best in authentic jungle, hardcore, oldskool, and rolling breaks.",
  },
  {
    id: "mon-02",
    dj: "DJ Mods (Bi-Weekly)",
    showName: "Monday Drivetime Tech",
    genre: "House / Tech House / Garage",
    day: "MON",
    startTime: "18:00",
    endTime: "20:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marcus-vance.jpg",
    isLive: false,
    bio: "Drivetime bi-weekly Monday vibes delivering upfront tech house and a sprinkling of oldskool garage.",
  },
  {
    id: "mon-03",
    dj: "Elena Cruz",
    showName: "Underground Frequency",
    genre: "UK Garage / 2-Step",
    day: "MON",
    startTime: "20:00",
    endTime: "22:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/elena-cruz.jpg",
    isLive: false,
  },
  {
    id: "mon-04",
    dj: "DJ Rapid",
    showName: "Night Shift D&B",
    genre: "Drum & Bass",
    day: "MON",
    startTime: "22:00",
    endTime: "00:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/dj-rapid.jpg",
    isLive: false,
  },

  // ── TUESDAY ───────────────────────────────────────────────────────
  {
    id: "tue-01",
    dj: "Marc Anthony",
    showName: "Midweek Grooves",
    genre: "UK Garage",
    day: "TUE",
    startTime: "10:00",
    endTime: "12:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marc-anthony.jpg",
  },
  {
    id: "tue-02",
    dj: "Anton James",
    showName: "Deep Resonance",
    genre: "Deep House",
    day: "TUE",
    startTime: "14:00",
    endTime: "16:00",
    channel: "DIVINE:CHILL",
    avatarUrl: "/images/djs/anton-james.jpg",
  },
  {
    id: "tue-03",
    dj: "Marcus Vance",
    showName: "DIVINE:TV Visual Set",
    genre: "Tech House",
    day: "TUE",
    startTime: "19:00",
    endTime: "21:00",
    channel: "DIVINE:TV",
    avatarUrl: "/images/djs/marcus-vance.jpg",
  },

  // ── WEDNESDAY ─────────────────────────────────────────────────────
  {
    id: "wed-01",
    dj: "Anton James",
    showName: "The Wednesday House Lunch",
    genre: "Classic House / Acid House",
    day: "WED",
    startTime: "12:00",
    endTime: "14:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/anton-james.jpg",
    bio: "Rolling everything house music old and new direct on DAB across Hertfordshire.",
  },
  {
    id: "wed-02",
    dj: "Andrew Jackson",
    showName: "Vocal & Acid House Odyssey",
    genre: "Vocal House / Acid",
    day: "WED",
    startTime: "14:00",
    endTime: "16:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marcus-vance.jpg",
  },
  {
    id: "wed-03",
    dj: "DJ Rollin",
    showName: "Midweek Pressure",
    genre: "Jungle / Drum & Bass",
    day: "WED",
    startTime: "20:00",
    endTime: "22:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/mc-icen.jpg",
  },

  // ── THURSDAY ──────────────────────────────────────────────────────
  {
    id: "thu-01",
    dj: "DJ Danny Hectic B",
    showName: "Thursday Night Sovereign Warm-up",
    genre: "Soulful Amapiano / Deep House",
    day: "THU",
    startTime: "18:00",
    endTime: "20:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/danny-hectic.jpg",
    bio: "Exclusive live studio session preparing the capital for the weekend with authentic underground rhythms.",
  },
  {
    id: "thu-02",
    dj: "Marcus Vance",
    showName: "DIVINE:TV Studio Broadcast",
    genre: "Tech House / Minimal",
    day: "THU",
    startTime: "20:00",
    endTime: "22:00",
    channel: "DIVINE:TV",
    avatarUrl: "/images/djs/marcus-vance.jpg",
  },

  // ── FRIDAY ────────────────────────────────────────────────────────
  {
    id: "fri-01",
    dj: "Elena Cruz",
    showName: "Weekend Warm-up Live",
    genre: "UK Garage / 2-Step",
    day: "FRI",
    startTime: "18:00",
    endTime: "20:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/elena-cruz.jpg",
  },
  {
    id: "fri-02",
    dj: "DJ Danny Hectic B",
    showName: "Friday Night Hectic Sessions",
    genre: "Soulful House / Amapiano",
    day: "FRI",
    startTime: "20:00",
    endTime: "22:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/danny-hectic.jpg",
  },
  {
    id: "fri-03",
    dj: "DJ Rapid & MC Immense",
    showName: "Friday Night Bass Explosion",
    genre: "Drum & Bass",
    day: "FRI",
    startTime: "22:00",
    endTime: "00:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/dj-rapid.jpg",
  },

  // ── SATURDAY ──────────────────────────────────────────────────────
  {
    id: "sat-01",
    dj: "Marc Anthony",
    showName: "The Saturday UKG Anthem Show",
    genre: "Garage / 2-Step",
    day: "SAT",
    startTime: "10:00",
    endTime: "12:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marc-anthony.jpg",
  },
  {
    id: "sat-02",
    dj: "DJ Rapid & MC Immense",
    showName: "Saturday Drum & Bass Session",
    genre: "Drum & Bass / Jungle",
    day: "SAT",
    startTime: "12:00",
    endTime: "14:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/dj-rapid.jpg",
  },
  {
    id: "sat-03",
    dj: "DJ Rollin & MC Icen",
    showName: "ROLLIN (Bi-Weekly) / RAMPA",
    genre: "Jungle / Drum & Bass / Oldskool",
    day: "SAT",
    startTime: "18:00",
    endTime: "20:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/mc-icen.jpg",
  },
  {
    id: "sat-04",
    dj: "DJ Danny Hectic B",
    showName: "The Prime Saturday Night Gala",
    genre: "Soulful House / Amapiano",
    day: "SAT",
    startTime: "20:00",
    endTime: "22:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/danny-hectic.jpg",
    isLive: true,
  },
  {
    id: "sat-05",
    dj: "DJ Rapid",
    showName: "Midnight Bass Therapy",
    genre: "Heavy D&B / Jungle",
    day: "SAT",
    startTime: "22:00",
    endTime: "00:00",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/dj-rapid.jpg",
  },

  // ── SUNDAY ────────────────────────────────────────────────────────
  {
    id: "sun-01",
    dj: "Anton James",
    showName: "Sunday Morning Soul Recovery",
    genre: "Soulful House / Balearic",
    day: "SUN",
    startTime: "10:00",
    endTime: "12:00",
    channel: "DIVINE:CHILL",
    avatarUrl: "/images/djs/anton-james.jpg",
  },
  {
    id: "sun-02",
    dj: "Bit2Beat",
    showName: "Pure Audio Delight",
    genre: "Club / Positive Energy / House",
    day: "SUN",
    startTime: "20:00",
    endTime: "22:00",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marcus-vance.jpg",
    bio: "Join Bit2Beat every Sunday for 2 hours of pure audio delight, euphoric club anthems, and uplifting positive energy!",
  },
];

// ─── Upcoming Events & Club Nights (Beating Centreforce) ────────────
export const EVENTS: EventItem[] = [
  {
    id: "divine-fabric-launch",
    title: "DIVINE x FABRIC LONDON: Heavyweight DAB Launch Party",
    venue: "Fabric London (Room 1 & Room 2)",
    location: "77A Charterhouse St, London EC1M 6HJ",
    date: "Saturday, 24 October 2026",
    doors: "22:00 - 06:00",
    price: "£25.00",
    lineup: [
      "DJ Danny Hectic B",
      "DJ Rapid & MC Immense",
      "Elena Cruz",
      "Marc Anthony",
      "MC Icen & DJ Rollin",
      "Special Secret Guests",
    ],
    ticketUrl: "https://www.skiddle.com/",
    category: "CLUB NIGHT",
  },
  {
    id: "divine-sub-warehouse",
    title: "DIVINE:SUB Sound System Warehouse Takeover",
    venue: "E1 London",
    location: "110 Pennington St, London E1W 2BB",
    date: "Friday, 13 November 2026",
    doors: "23:00 - 07:00",
    price: "£22.50",
    lineup: ["DJ Rapid", "MC Immense", "Krucial", "DJ Rollin", "Sound System Crew"],
    ticketUrl: "https://www.skiddle.com/",
    category: "WAREHOUSE",
  },
  {
    id: "divine-chill-rooftop",
    title: "DIVINE:CHILL Sunset Balearic Penthouse Sessions",
    venue: "Sky Garden Rooftop Terrace",
    location: "1 Sky Garden Walk, London EC3M 8AF",
    date: "Sunday, 20 December 2026",
    doors: "16:00 - 23:00",
    price: "£35.00",
    lineup: ["Anton James", "Elena Cruz (Sunset Balearic Set)", "Bit2Beat"],
    ticketUrl: "https://www.skiddle.com/",
    category: "ROOFTOP",
  },
  {
    id: "divine-tenerife-weekender",
    title: "DIVINE Presents: Tenerife Weekender 2027",
    venue: "Playa de las Américas",
    location: "Tenerife, Canary Islands",
    date: "14 - 18 May 2027",
    doors: "5 Days / 4 Nights",
    price: "£189.00 Early Bird",
    lineup: ["Full 40+ DIVINE DJ Roster", "Boat Parties", "Pool Parties", "VIP Beach Club"],
    ticketUrl: "https://www.skiddle.com/",
    category: "FESTIVAL",
  },
];

// ─── Merch Collection: DIVINE ATELIER (Beating Centreforce Merch) ───
export const MERCH: MerchItem[] = [
  {
    id: "divine-hoodie-gold",
    name: "DIVINE Heavyweight 480gsm Metallic Gold Foil Hoodie",
    price: 75.0,
    category: "HOODIES",
    description: "Custom ultra-dense 480gsm organic cotton French Terry. High-definition 3D embossed metallic gold 'DIVINE' typography on chest with branded woven neck labels.",
    tag: "SIGNATURE BESTSELLER",
    colors: ["True Black / Gold", "Deep Zinc / Gold"],
  },
  {
    id: "divine-slipmats-pair",
    name: "DIVINE 1210 Edition Gold Foil Turntable Slipmats (Pair)",
    price: 28.0,
    category: "ACCESSORIES",
    description: "High-density glazed polyester felt engineered for professional vinyl scratching and mixing. Features circular metallic gold 'THE HIGHER STATE OF AUDIO' emblem.",
    tag: "PRO DJ EDITION",
  },
  {
    id: "divine-acid-tee",
    name: "DIVINE London Underground Acid-Wash Boxy Tee",
    price: 42.0,
    category: "TEES",
    description: "Heavy 260gsm vintage-wash luxury jersey. Relaxed boxy London streetwear silhouette with subtle tonal 'DIVINE' emblem on chest and DAB frequency print on spine.",
    tag: "LIMITED RUN",
    colors: ["Washed Charcoal", "True Black"],
  },
  {
    id: "divine-dj-flightbag",
    name: "DIVINE Official Pioneer CDJ / Laptop Hard Flight Bag",
    price: 95.0,
    category: "DJ GEAR",
    description: "Ballistic water-resistant nylon shell with plush velvet interior, gold anodized zippers, cable organizers, and laser-engraved gold metal DIVINE badge.",
    tag: "ESSENTIAL",
  },
];

// ─── Archive / Listen Back Shows (Over 15,000 shows on Mixcloud) ────
export const ARCHIVE_SHOWS: ArchiveShow[] = [
  {
    id: "arch-01",
    title: "The Sovereign Sound Session #482",
    dj: "DJ Danny Hectic B",
    genre: "Soulful Amapiano & Deep House",
    date: "12 Sep 2026",
    duration: "2 hr 04 min",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/danny-hectic.jpg",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    listenCount: 8420,
  },
  {
    id: "arch-02",
    title: "Rollin Jungle & D&B Showcase Live",
    dj: "DJ Rollin & MC Icen",
    genre: "Jungle / Drum & Bass",
    date: "11 Sep 2026",
    duration: "1 hr 58 min",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/mc-icen.jpg",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    listenCount: 6190,
  },
  {
    id: "arch-03",
    title: "Pure UK Garage Morning Vault #192",
    dj: "Marc Anthony",
    genre: "UK Garage & 2-Step",
    date: "10 Sep 2026",
    duration: "2 hr 01 min",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/marc-anthony.jpg",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    listenCount: 5740,
  },
  {
    id: "arch-04",
    title: "Drum & Bass Saturday Dubplate Pressure",
    dj: "DJ Rapid & MC Immense",
    genre: "Drum & Bass",
    date: "09 Sep 2026",
    duration: "2 hr 15 min",
    channel: "DIVINE:SUB",
    avatarUrl: "/images/djs/dj-rapid.jpg",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    listenCount: 7890,
  },
  {
    id: "arch-05",
    title: "Classic & Acid House Odyssey #310",
    dj: "Anton James",
    genre: "Classic House",
    date: "08 Sep 2026",
    duration: "2 hr 00 min",
    channel: "DIVINE:ONE",
    avatarUrl: "/images/djs/anton-james.jpg",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    listenCount: 4320,
  },
  {
    id: "arch-06",
    title: "DIVINE:TV Live Visual Broadcast Special",
    dj: "Elena Cruz",
    genre: "UKG / Bassline",
    date: "07 Sep 2026",
    duration: "1 hr 45 min",
    channel: "DIVINE:TV",
    avatarUrl: "/images/djs/elena-cruz.jpg",
    mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
    listenCount: 9650,
  },
];

// ─── Studio Information & DAB Transmission ──────────────────────────
export const STATION_INFO = {
  name: "DIVINE",
  legalName: "Divine Radio London DAB",
  slogan: "The Higher State of Audio.",
  subSlogan: "Music Sounds Better With You • Sound of the Underground",
  studioWhatsApp: "07597 611013",
  studioPhone: "+44 7597 611013",
  whatsAppLink: "https://wa.me/447597611013?text=Live%20shout-out%20to%20the%20DIVINE%20studio%20from:",
  mixcloudUrl: "https://www.mixcloud.com/DivineRadio/",
  iosAppUrl: "https://apps.apple.com/gb/app/divine-radio-london/id1587675847",
  androidAppUrl: "https://play.google.com/store/apps/details?id=uk.radio.divineradio&hl=en_GB",
  archiveCount: "15,000+",
  listenerPopulation: "813,000+",
  dabCoverageTowns: [
    "Watford",
    "St Albans",
    "Hemel Hempstead",
    "Welwyn Garden City",
    "Hatfield",
    "Borehamwood",
    "Hertford",
    "Bushey",
    "Rickmansworth",
    "Potters Bar",
    "Berkhamsted",
    "Abbots Langley",
    "Ware",
    "Radlett",
    "Chorleywood",
    "Croxley Green",
    "Redbourn",
    "North & South East London",
  ],
  sponsors: [
    { name: "Pioneer DJ", role: "Official Pro Decks & Mixers" },
    { name: "Technics", role: "Reference Vinyl Turntables" },
    { name: "Sennheiser", role: "Broadcast Reference Headphones" },
    { name: "Shure", role: "Studio Vocal Microphones" },
    { name: "PreSonus", role: "Studio Reference Audio Monitors" },
    { name: "Denon Prime", role: "Digital Media Players" },
    { name: "Clarity Car Spa", role: "VIP Automotive Partner" },
  ],
};
